In [61]:
import pandas as pd
import numpy as np

In [62]:
df=pd.read_excel('C:/Users/Arshad/Downloads/GS-stata.xlsx')

In [63]:
df

,Country Name,Series Name,Unnamed: 2,Unnamed: 3,Unnamed: 4,2000,2001,2002,2003,2004,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,Australia,General government final consumption expenditu...,NaN,NaN,NaN,17.787098,17.783158,17.544246,17.595386,17.495375,...,17.479803,17.343937,17.242653,17.591547,17.999002,17.810750,17.986232,17.840380,17.697384,18.060742
1,China,General government final consumption expenditu...,NaN,NaN,NaN,16.633346,16.089997,15.603177,14.676877,13.902021,...,13.949006,13.490259,13.196161,13.218093,12.845916,13.216802,13.475446,13.588584,13.375250,14.036066
2,India,General government final consumption expenditu...,NaN,NaN,NaN,11.947835,11.761450,11.314095,10.876210,10.404702,...,9.802470,9.862116,10.538481,11.459667,11.007608,11.084457,10.683856,10.295160,10.440857,10.428291
3,Japan,General government final consumption expenditu...,NaN,NaN,NaN,16.852039,17.534689,18.127132,18.193359,18.102930,...,17.952903,17.945612,18.359443,19.634648,19.491604,20.187787,20.252438,20.165763,20.153033,19.818027
4,"Korea, Rep.",General government final consumption expenditu...,NaN,NaN,NaN,11.338342,12.186803,12.134766,12.467763,12.789334,...,13.819209,13.928599,14.644848,15.169299,14.471457,14.585726,14.833439,15.003532,15.121952,15.009450
5,Mexico,General government final consumption expenditu...,NaN,NaN,NaN,9.515219,9.881126,10.377716,11.033790,10.487290,...,10.344423,10.405381,10.729519,11.916964,11.771363,11.777083,11.946734,12.191387,12.202265,12.330907
6,Switzerland,General government final consumption expenditu...,NaN,NaN,NaN,11.577088,11.678320,12.063200,12.246455,12.006337,...,11.313620,10.909267,11.043443,11.776340,11.602090,11.681364,11.858860,11.931751,11.970933,11.933068
7,Turkey,General government final consumption expenditu...,NaN,NaN,NaN,11.986495,12.740597,12.933919,12.702239,12.439613,...,13.014316,13.499999,13.705273,15.770384,14.972658,13.702279,14.232380,14.124618,14.091517,13.877744
8,United Kingdom,General government final consumption expenditu...,NaN,NaN,NaN,16.780617,17.413134,18.190897,18.861145,19.491974,...,19.816085,19.644269,20.446925,22.029152,21.658540,20.969174,20.777471,20.124022,19.829546,19.493754
9,United States,General government final consumption expenditu...,NaN,NaN,NaN,14.026010,14.528614,15.041861,15.246542,15.168881,...,15.008319,15.214797,15.988710,16.822024,16.743157,16.160469,15.533604,15.085069,14.641337,14.359747
10,Angola,General government final consumption expenditu...,NaN,NaN,NaN,17.842634,25.154633,19.130579,21.854259,14.312060,...,15.341722,15.536935,16.814611,19.898590,17.042344,18.235861,17.842634,21.621949,17.975660,16.432832
11,Botswana,General government final consumption expenditu...,NaN,NaN,NaN,24.902729,23.486632,22.379126,22.008716,20.532344,...,17.037852,17.594781,20.351259,21.089543,19.756506,18.486708,19.291427,18.548308,19.934210,20.577449
12,Burkina Faso,General government final consumption expenditu...,NaN,NaN,NaN,20.657537,25.793966,21.184374,19.872285,20.774584,...,21.677307,23.852384,21.364409,21.633004,20.640300,20.565332,20.844185,21.319948,22.553831,23.191706
13,Burundi,General government final consumption expenditu...,NaN,NaN,NaN,14.856698,15.533074,14.732987,17.461335,19.227266,...,15.200000,19.000001,20.200001,19.700001,21.900000,22.900000,23.299999,24.700000,25.900006,22.421115
14,Cameroon,General government final consumption expenditu...,NaN,NaN,NaN,10.685927,11.696386,11.284429,11.519731,11.211059,...,10.294519,10.350120,11.105159,11.602965,11.389642,12.111140,12.218167,12.326578,12.153892,12.276779
15,Canada,General government final consumption expenditu...,NaN,NaN,NaN,19.170198,19.578257,19.849141,19.966616,19.483781,...,19.305096,19.301037,19.768555,22.020206,21.526041,21.195341,21.108641,20.755803,20.314595,20.926345
16,Chile,General government final consumption expenditu...,NaN,NaN,NaN,12.082563,12.121559,12.219726,11.719735,10.961714,...,9.925310,10.252720,11.071389,12.416885,12.108741,11.913488,11.924860,12.300820,12.700984,12.993893
17,Colombia,General government final consumption expenditu...,NaN,NaN,NaN,16.472851,16.566232,16.040893,15.610347,15.681598,...,13.917541,13.761731,13.169829,13.798427,13.782345,13.368813,13.488092,14.106535,14.243751,14.811630
18,"Congo, Rep.",General government final consumption expenditu...,NaN,NaN,NaN,11.568070,14.089733,18.357167,17.358992,14.972718,...,13.929155,16.971163,11.947962,12.231958,10.440160,9.986844,14.649960,13.550848,13.836504,18.136899
19,Cote d'Ivoire,General government final consumption expenditu...,NaN,NaN,NaN,14.351020,13.614935,12.977068,14.803452,14.895031,...,13.591615,13.338576,12.669763,12.635347,12.177588,11.246138,12.321342,12.262661,12.331497,11.940737
20,Czech Republic,General government final consumption expenditu...,NaN,NaN,NaN,19.871076,19.825613,21.287128,22.260426,20.982294,...,20.243749,19.422169,19.404928,20.997789,20.828278,20.158909,19.805306,20.155642,19.684667,19.216094
21,Denmark,General government final consumption expenditu...,NaN,NaN,NaN,23.873765,24.324912,24.869054,25.038024,24.933901,...,24.203538,24.337963,25.100890,27.935000,27.365848,26.564666,26.471456,26.007488,25.785652,25.469200
22,Ethiopia,General government final consumption expenditu...,NaN,NaN,NaN,8.302189,8.955474,9.249592,8.302189,8.955474,...,9.013789,9.013789,8.302189,8.955474,9.249592,10.318246,8.302189,8.955474,9.249592,9.013789
23,Ghana,General government final consumption expenditu...,NaN,NaN,NaN,10.171616,9.722364,9.872770,11.533203,12.172812,...,8.870722,8.524940,8.731660,7.574244,7.069499,13.788598,11.764346,10.927904,10.432040,9.656949
24,Hungary,General government final consumption expenditu...,NaN,NaN,NaN,21.197290,21.083254,21.864448,23.009379,22.055929,...,22.017401,20.811082,21.399617,22.071323,21.570079,20.718851,20.058850,19.763101,20.062067,19.815902
25,Iceland,General government final consumption expenditu...,NaN,NaN,NaN,22.495898,22.677670,24.328179,25.067462,24.030522,...,23.671453,23.074919,23.673253,24.973056,24.683750,24.659108,24.435771,24.100500,23.935643,23.393615
26,Israel,General government final consumption expenditu...,NaN,NaN,NaN,24.319335,25.516961,26.877227,26.068647,24.687019,...,23.923610,23.003929,22.979215,22.868097,22.716380,22.462318,22.769270,22.772386,22.723644,22.463818
27,Kenya,General government final consumption expenditu...,NaN,NaN,NaN,15.054292,15.972912,17.078000,18.131319,17.860066,...,14.346999,14.629611,15.673979,15.214472,14.169029,14.011634,13.857935,14.139584,13.890408,14.087628
28,Lesotho,General government final consumption expenditu...,NaN,NaN,NaN,34.849600,37.313091,34.577779,36.473413,35.244041,...,35.244041,35.826752,35.826752,40.444222,37.370675,34.849600,37.313091,34.577779,36.473413,35.244041
29,Madagascar,General government final consumption expenditu...,NaN,NaN,NaN,9.042819,9.090523,8.135258,9.227847,6.940740,...,8.952796,19.029039,14.076977,12.508634,13.116075,14.117114,15.007693,15.646670,15.800002,15.140320
30,Malawi,General government final consumption expenditu...,NaN,NaN,NaN,14.577839,15.808831,10.507192,9.397913,9.439587,...,11.394116,10.993956,13.228003,15.946307,14.231410,13.404089,14.384903,16.367254,12.537790,13.899497
31,Mali,General government final consumption expenditu...,NaN,NaN,NaN,16.417436,14.998356,15.360704,15.566553,15.460917,...,13.262240,13.945759,15.567289,14.569911,15.687645,18.793164,15.484434,16.678302,16.256527,16.371548
32,Mauritius,General government final consumption expenditu...,NaN,NaN,NaN,14.251782,13.925942,14.160138,14.079492,14.202052,...,14.123929,12.435593,12.464556,13.922250,13.818488,13.463603,13.357708,14.604844,14.822656,14.933409
33,Namibia,General government final consumption expenditu...,NaN,NaN,NaN,23.961595,23.288384,22.049486,22.755041,20.766556,...,19.839790,23.861896,21.796362,23.858523,25.554097,23.188953,24.970580,25.988667,26.242256,25.625806
34,Niger,General government final consumption expenditu...,NaN,NaN,NaN,13.038928,12.383773,12.235213,15.581354,16.325645,...,15.008407,15.649523,16.093129,17.372688,14.752625,15.563984,14.248418,14.167846,15.421307,17.888742
35,Nigeria,General government final consumption expenditu...,NaN,NaN,NaN,2.123442,1.990621,1.340488,0.951747,4.787637,...,5.125842,9.448340,9.428957,8.649948,8.848100,8.572152,8.228178,7.155219,6.464486,6.688120
36,Norway,General government final consumption expenditu...,NaN,NaN,NaN,18.886699,20.062699,21.669530,21.991910,20.803300,...,18.639301,18.728706,18.506649,21.598440,21.340208,20.918808,20.742004,21.109597,21.867739,23.239021
37,Poland,General government final consumption expenditu...,NaN,NaN,NaN,18.075665,18.658162,18.630253,18.902037,18.279814,...,18.477432,18.109304,18.603123,18.707878,19.119656,18.051421,17.929331,18.130841,18.178653,18.039180
38,Rwanda,General government final consumption expenditu...,NaN,NaN,NaN,18.672265,18.699722,19.570004,19.209807,18.351296,...,17.150599,15.261422,13.255700,13.623472,14.053528,12.777049,13.692655,13.541949,15.070941,14.643092
39,Senegal,General government final consumption expenditu...,NaN,NaN,NaN,12.790520,12.605314,13.266417,13.001447,13.459063,...,13.652999,13.001447,13.459063,13.296059,13.652999,13.459063,13.296059,13.652999,14.734527,14.299580
40,Seychelles,General government final consumption expenditu...,NaN,NaN,NaN,42.207816,41.619959,47.191560,44.312807,38.934121,...,39.450627,35.287323,27.386028,28.856325,27.287484,27.432555,27.480526,17.960067,19.754550,20.325795
41,South Africa,General government final consumption expenditu...,NaN,NaN,NaN,18.386937,18.534064,18.805190,19.057888,19.157564,...,18.153528,17.814015,18.657925,19.864480,20.229638,19.862240,20.259928,20.574980,20.795677,20.454388
42,Sweden,General government final consumption expenditu...,NaN,NaN,NaN,24.672510,24.878480,25.596685,25.872739,25.184388,...,24.797460,24.308854,24.747118,26.084046,25.056826,24.995980,25.822932,26.295337,26.161414,25.813772
43,Tanzania,General government final consumption expenditu...,NaN,NaN,NaN,7.851180,8.003682,8.864388,10.378315,11.475903,...,11.889825,13.109265,11.317596,12.333057,10.362204,9.696879,10.427013,10.045237,9.867791,9.927295
44,Togo,General government final consumption expenditu...,NaN,NaN,NaN,12.486586,13.438282,10.575789,10.857985,11.035090,...,14.998356,13.627261,12.453857,11.451616,13.362835,16.900790,15.302128,15.079523,16.542943,17.989406
45,Uganda,General government final consumption expenditu...,NaN,NaN,NaN,14.504324,15.581845,16.792470,15.745053,13.887302,...,14.102312,12.893035,11.210887,9.225141,9.594207,12.787480,8.215254,7.993838,8.483944,9.302974
46,United Arab Emirates,General government final consumption expenditu...,NaN,NaN,NaN,9.914024,9.914024,10.146486,9.750234,8.746698,...,6.917822,6.732998,7.296836,10.234143,10.031072,9.953315,9.730440,10.984428,10.931864,12.428578
47,Zambia,General government final consumption expenditu...,NaN,NaN,NaN,12.184391,14.523946,14.780585,9.379639,10.245500,...,14.523946,14.780585,9.379639,10.245500,9.379639,10.245500,11.897298,12.184391,14.523946,14.780585

In [65]:
df2=df.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'], axis=1, inplace=True)

In [66]:

df.set_index('Country Name')

,Series Name,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country Name,,,,,,,,,,,,,,,,,
Australia,General government final consumption expenditu...,17.787098,17.783158,17.544246,17.595386,17.495375,17.561589,17.479803,17.343937,17.242653,17.591547,17.999002,17.810750,17.986232,17.840380,17.697384,18.060742
China,General government final consumption expenditu...,16.633346,16.089997,15.603177,14.676877,13.902021,13.995045,13.949006,13.490259,13.196161,13.218093,12.845916,13.216802,13.475446,13.588584,13.375250,14.036066
India,General government final consumption expenditu...,11.947835,11.761450,11.314095,10.876210,10.404702,10.366140,9.802470,9.862116,10.538481,11.459667,11.007608,11.084457,10.683856,10.295160,10.440857,10.428291
Japan,General government final consumption expenditu...,16.852039,17.534689,18.127132,18.193359,18.102930,18.117221,17.952903,17.945612,18.359443,19.634648,19.491604,20.187787,20.252438,20.165763,20.153033,19.818027
"Korea, Rep.",General government final consumption expenditu...,11.338342,12.186803,12.134766,12.467763,12.789334,13.282861,13.819209,13.928599,14.644848,15.169299,14.471457,14.585726,14.833439,15.003532,15.121952,15.009450
Mexico,General government final consumption expenditu...,9.515219,9.881126,10.377716,11.033790,10.487290,10.521707,10.344423,10.405381,10.729519,11.916964,11.771363,11.777083,11.946734,12.191387,12.202265,12.330907
Switzerland,General government final consumption expenditu...,11.577088,11.678320,12.063200,12.246455,12.006337,11.822565,11.313620,10.909267,11.043443,11.776340,11.602090,11.681364,11.858860,11.931751,11.970933,11.933068
Turkey,General government final consumption expenditu...,11.986495,12.740597,12.933919,12.702239,12.439613,12.304866,13.014316,13.499999,13.705273,15.770384,14.972658,13.702279,14.232380,14.124618,14.091517,13.877744
United Kingdom,General government final consumption expenditu...,16.780617,17.413134,18.190897,18.861145,19.491974,19.699071,19.816085,19.644269,20.446925,22.029152,21.658540,20.969174,20.777471,20.124022,19.829546,19.493754
United States,General government final consumption expenditu...,14.026010,14.528614,15.041861,15.246542,15.168881,15.055298,15.008319,15.214797,15.988710,16.822024,16.743157,16.160469,15.533604,15.085069,14.641337,14.359747
Angola,General government final consumption expenditu...,17.842634,25.154633,19.130579,21.854259,14.312060,16.029037,15.341722,15.536935,16.814611,19.898590,17.042344,18.235861,17.842634,21.621949,17.975660,16.432832
Botswana,General government final consumption expenditu...,24.902729,23.486632,22.379126,22.008716,20.532344,19.400745,17.037852,17.594781,20.351259,21.089543,19.756506,18.486708,19.291427,18.548308,19.934210,20.577449
Burkina Faso,General government final consumption expenditu...,20.657537,25.793966,21.184374,19.872285,20.774584,19.769418,21.677307,23.852384,21.364409,21.633004,20.640300,20.565332,20.844185,21.319948,22.553831,23.191706
Burundi,General government final consumption expenditu...,14.856698,15.533074,14.732987,17.461335,19.227266,14.100000,15.200000,19.000001,20.200001,19.700001,21.900000,22.900000,23.299999,24.700000,25.900006,22.421115
Cameroon,General government final consumption expenditu...,10.685927,11.696386,11.284429,11.519731,11.211059,10.953581,10.294519,10.350120,11.105159,11.602965,11.389642,12.111140,12.218167,12.326578,12.153892,12.276779
Canada,General government final consumption expenditu...,19.170198,19.578257,19.849141,19.966616,19.483781,19.137095,19.305096,19.301037,19.768555,22.020206,21.526041,21.195341,21.108641,20.755803,20.314595,20.926345
Chile,General government final consumption expenditu...,12.082563,12.121559,12.219726,11.719735,10.961714,10.576583,9.925310,10.252720,11.071389,12.416885,12.108741,11.913488,11.924860,12.300820,12.700984,12.993893
Colombia,General government final consumption expenditu...,16.472851,16.566232,16.040893,15.610347,15.681598,13.998299,13.917541,13.761731,13.169829,13.798427,13.782345,13.368813,13.488092,14.106535,14.243751,14.811630
"Congo, Rep.",General government final consumption expenditu...,11.568070,14.089733,18.357167,17.358992,14.972718,12.994051,13.929155,16.971163,11.947962,12.231958,10.440160,9.986844,14.649960,13.550848,13.836504,18.136899
Cote d'Ivoire,General government final consumption expenditu...,14.351020,13.614935,12.977068,14.803452,14.895031,14.427445,13.591615,13.338576,12.669763,12.635347,12.177588,11.246138,12.321342,12.262661,12.331497,11.940737
Czech Republic,General government final consumption expenditu...,19.871076,19.825613,21.287128,22.260426,20.982294,20.679579,20.243749,19.422169,19.404928,20.997789,20.828278,20.158909,19.805306,20.155642,19.684667,19.216094
Denmark,General government final consumption expenditu...,23.873765,24.324912,24.869054,25.038024,24.933901,24.498689,24.203538,24.337963,25.100890,27.935000,27.365848,26.564666,26.471456,26.007488,25.785652,25.469200
Ethiopia,General government final consumption expenditu...,8.302189,8.955474,9.249592,8.302189,8.955474,9.249592,9.013789,9.013789,8.302189,8.955474,9.249592,10.318246,8.302189,8.955474,9.249592,9.013789
Ghana,General government final consumption expenditu...,10.171616,9.722364,9.872770,11.533203,12.172812,15.308165,8.870722,8.524940,8.731660,7.574244,7.069499,13.788598,11.764346,10.927904,10.432040,9.656949
Hungary,General government final consumption expenditu...,21.197290,21.083254,21.864448,23.009379,22.055929,22.167686,22.017401,20.811082,21.399617,22.071323,21.570079,20.718851,20.058850,19.763101,20.062067,19.815902
Iceland,General government final consumption expenditu...,22.495898,22.677670,24.328179,25.067462,24.030522,23.780400,23.671453,23.074919,23.673253,24.973056,24.683750,24.659108,24.435771,24.100500,23.935643,23.393615
Israel,General government final consumption expenditu...,24.319335,25.516961,26.877227,26.068647,24.687019,24.230141,23.923610,23.003929,22.979215,22.868097,22.716380,22.462318,22.769270,22.772386,22.723644,22.463818
Kenya,General government final consumption expenditu...,15.054292,15.972912,17.078000,18.131319,17.860066,17.380212,14.346999,14.629611,15.673979,15.214472,14.169029,14.011634,13.857935,14.139584,13.890408,14.087628
Lesotho,General government final consumption expenditu...,34.849600,37.313091,34.577779,36.473413,35.244041,35.826752,35.244041,35.826752,35.826752,40.444222,37.370675,34.849600,37.313091,34.577779,36.473413,35.244041
Madagascar,General government final consumption expenditu...,9.042819,9.090523,8.135258,9.227847,6.940740,9.197625,8.952796,19.029039,14.076977,12.508634,13.116075,14.117114,15.007693,15.646670,15.800002,15.140320
Malawi,General government final consumption expenditu...,14.577839,15.808831,10.507192,9.397913,9.439587,10.787802,11.394116,10.993956,13.228003,15.946307,14.231410,13.404089,14.384903,16.367254,12.537790,13.899497
Mali,General government final consumption expenditu...,16.417436,14.998356,15.360704,15.566553,15.460917,13.846429,13.262240,13.945759,15.567289,14.569911,15.687645,18.793164,15.484434,16.678302,16.256527,16.371548
Mauritius,General government final consumption expenditu...,14.251782,13.925942,14.160138,14.079492,14.202052,14.522659,14.123929,12.435593,12.464556,13.922250,13.818488,13.463603,13.357708,14.604844,14.822656,14.933409
Namibia,General government final consumption expenditu...,23.961595,23.288384,22.049486,22.755041,20.766556,19.663450,19.839790,23.861896,21.796362,23.858523,25.554097,23.188953,24.970580,25.988667,26.242256,25.625806
Niger,General government final consumption expenditu...,13.038928,12.383773,12.235213,15.581354,16.325645,15.597684,15.008407,15.649523,16.093129,17.372688,14.752625,15.563984,14.248418,14.167846,15.421307,17.888742
Nigeria,General government final consumption expenditu...,2.123442,1.990621,1.340488,0.951747,4.787637,4.544547,5.125842,9.448340,9.428957,8.649948,8.848100,8.572152,8.228178,7.155219,6.464486,6.688120
Norway,General government final consumption expenditu...,18.886699,20.062699,21.669530,21.991910,20.803300,19.442087,18.639301,18.728706,18.506649,21.598440,21.340208,20.918808,20.742004,21.109597,21.867739,23.239021
Poland,General government final consumption expenditu...,18.075665,18.658162,18.630253,18.902037,18.279814,18.297007,18.477432,18.109304,18.603123,18.707878,19.119656,18.051421,17.929331,18.130841,18.178653,18.039180
Rwanda,General government final consumption expenditu...,18.672265,18.699722,19.570004,19.209807,18.351296,18.175240,17.150599,15.261422,13.255700,13.623472,14.053528,12.777049,13.692655,13.541949,15.070941,14.643092
Senegal,General government final consumption expenditu...,12.790520,12.605314,13.266417,13.001447,13.459063,13.296059,13.652999,13.001447,13.459063,13.296059,13.652999,13.459063,13.296059,13.652999,14.734527,14.299580
Seychelles,General government final consumption expenditu...,42.207816,41.619959,47.191560,44.312807,38.934121,34.592441,39.450627,35.287323,27.386028,28.856325,27.287484,27.432555,27.480526,17.960067,19.754550,20.325795
South Africa,General government final consumption expenditu...,18.386937,18.534064,18.805190,19.057888,19.157564,19.478189,18.153528,17.814015,18.657925,19.864480,20.229638,19.862240,20.259928,20.574980,20.795677,20.454388
Sweden,General government final consumption expenditu...,24.672510,24.878480,25.596685,25.872739,25.184388,25.054152,24.797460,24.308854,24.747118,26.084046,25.056826,24.995980,25.822932,26.295337,26.161414,25.813772
Tanzania,General government final consumption expenditu...,7.851180,8.003682,8.864388,10.378315,11.475903,11.918043,11.889825,13.109265,11.317596,12.333057,10.362204,9.696879,10.427013,10.045237,9.867791,9.927295
Togo,General government final consumption expenditu...,12.486586,13.438282,10.575789,10.857985,11.035090,13.001660,14.998356,13.627261,12.453857,11.451616,13.362835,16.900790,15.302128,15.079523,16.542943,17.989406
Uganda,General government final consumption expenditu...,14.504324,15.581845,16.792470,15.745053,13.887302,14.492763,14.102312,12.893035,11.210887,9.225141,9.594207,12.787480,8.215254,7.993838,8.483944,9.302974
United Arab Emirates,General government final consumption expenditu...,9.914024,9.914024,10.146486,9.750234,8.746698,7.872593,6.917822,6.732998,7.296836,10.234143,10.031072,9.953315,9.730440,10.984428,10.931864,12.428578
Zambia,General government final consumption expenditu...,12.184391,14.523946,14.780585,9.379639,10.245500,12.184391,14.523946,14.780585,9.379639,10.245500,9.379639,10.245500,11.897298,12.184391,14.523946,14.780585

In [67]:
df2 = pd.melt(df, id_vars=['Country Name','Series Name'],var_name='Year', value_name='value')
df2

,Country Name,Series Name,Year,value
0,Australia,General government final consumption expenditu...,2000,17.787098
1,China,General government final consumption expenditu...,2000,16.633346
2,India,General government final consumption expenditu...,2000,11.947835
3,Japan,General government final consumption expenditu...,2000,16.852039
4,"Korea, Rep.",General government final consumption expenditu...,2000,11.338342
...,...,...,...,...
763,Tanzania,General government final consumption expenditu...,2015,9.927295
764,Togo,General government final consumption expenditu...,2015,17.989406
765,Uganda,General government final consumption expenditu...,2015,9.302974
766,United Arab Emirates,General government final consumption expenditu...,2015,12.428578
767,Zambia,General government final consumption expenditu...,2015,14.780585

In [68]:
df3=pd.read_excel('C:/Users/Arshad/Documents/Salu/merge/data-stata-final.xlsx')
df3

,CountryName,Year,INFLATION,TOPEN,LogGDPPerCapita,MoneyGrowth,Fuelexports,Termoftrade,Exchangerate,DebttoGDPratio,Fuelexports_new,CountryName_new
0,1,2000,325.000000,152.547110,556.836318,303.735499,94.8,100.000000,10.040544,89.903000,94.800003,Angola
1,1,2001,152.600000,150.335795,527.333529,163.003104,95.7,91.048742,22.057862,80.173500,95.699997,Angola
2,1,2002,108.900000,105.301743,872.494492,156.340680,95.5,91.679598,43.530207,72.972000,95.500000,Angola
3,1,2003,98.224144,103.901227,982.960899,68.098314,94,100.707305,74.606301,59.770600,94.000000,Angola
4,1,2004,43.542107,103.579924,1255.564045,48.551965,93.7,120.307875,83.541363,51.953736,93.699997,Angola
...,...,...,...,...,...,...,...,...,...,...,...,...
763,49,2011,6.429397,76.212834,1672.949830,21.701980,.452859229,206.421612,4.861667,20.803322,0.452859,Zambia
764,49,2012,6.575900,79.099742,1763.094184,17.859427,1.249263734,192.563751,5.147500,24.910842,1.249264,Zambia
765,49,2013,6.977676,84.597289,1878.903489,20.791580,1.912876131,184.841705,5.396483,25.914770,1.912876,Zambia
766,49,2014,7.806876,80.063561,1763.056239,12.618085,1.149178466,178.079934,6.154167,33.605962,1.149179,Zambia
767,49,2015,10.110593,79.865155,1337.796315,35.192471,1.64272294,170.322273,8.631667,56.282192,1.642723,Zambia

In [69]:
df2.to_csv (r'C:/Users/Arshad/Documents/Salu/merge/gs-stata.csv')
df2

,Country Name,Series Name,Year,value
0,Australia,General government final consumption expenditu...,2000,17.787098
1,China,General government final consumption expenditu...,2000,16.633346
2,India,General government final consumption expenditu...,2000,11.947835
3,Japan,General government final consumption expenditu...,2000,16.852039
4,"Korea, Rep.",General government final consumption expenditu...,2000,11.338342
...,...,...,...,...
763,Tanzania,General government final consumption expenditu...,2015,9.927295
764,Togo,General government final consumption expenditu...,2015,17.989406
765,Uganda,General government final consumption expenditu...,2015,9.302974
766,United Arab Emirates,General government final consumption expenditu...,2015,12.428578
767,Zambia,General government final consumption expenditu...,2015,14.780585

In [70]:
df2.drop(['Series Name'], axis=1, inplace=True)

In [71]:
df2.rename({'value': 'General government final consumption expenditure'},axis=1, inplace=True )

In [72]:
df3.rename({'Country Name': 'CountryName','CountryName_new': 'Country Name', },axis=1, inplace=True )

In [73]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CountryName      768 non-null    int64
 1   Year             768 non-null    int64
 2   INFLATION        768 non-null    float64
 3   TOPEN            768 non-null    float64
 4   LogGDPPerCapita  768 non-null    float64
 5   MoneyGrowth      768 non-null    float64
 6   Fuelexports      768 non-null    object
 7   Termoftrade      768 non-null    float64
 8   Exchangerate     768 non-null    float64
 9   DebttoGDPratio   768 non-null    float64
 10  Fuelexports_new  767 non-null    float64
 11  Country Name     768 non-null    object
dtypes: float64(8), int64(2), object(2)
memory usage: 72.1+ KB

In [74]:
df2.Year=list(map(int, df2.Year))
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 3 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Country Name                                      768 non-null    object
 1   Year                                              768 non-null    int64
 2   General government final consumption expenditure  768 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 18.1+ KB

In [75]:
df4=pd.merge(df2, df3, on=['Country Name', 'Year'])

In [76]:
df4.head(10)

,Country Name,Year,General government final consumption expenditure,CountryName,INFLATION,TOPEN,LogGDPPerCapita,MoneyGrowth,Fuelexports,Termoftrade,Exchangerate,DebttoGDPratio,Fuelexports_new
0,Australia,2000,17.787098,2,4.457435,41.029011,21679.247840,3.739910,21.8804272,100.0,1.724827,19.458468,21.880426
1,China,2000,16.633346,9,0.347806,39.410539,959.372484,12.324782,3.143509612,100.0,8.278504,22.808933,3.143510
2,India,2000,11.947835,19,4.009436,26.900923,443.314193,15.171708,3.403651605,100.0,44.941605,73.648995,3.403652
3,Japan,2000,16.852039,21,-0.676579,19.819653,38532.040880,1.335565,.363218823,100.0,107.765498,143.778488,0.363219
4,"Korea, Rep.",2000,11.338342,23,2.259185,67.947192,11947.579130,25.425775,5.464777822,100.0,1130.957500,17.114014,5.464778
5,Mexico,2000,9.515219,29,9.491561,52.432682,7157.814500,-4.487431,9.666487834,100.0,9.455558,41.849951,9.666488
6,Switzerland,2000,11.577088,41,1.558518,98.105667,37868.296000,-16.930527,.409076278,100.0,1.688843,54.563193,0.409076
7,Turkey,2000,11.986495,44,54.915371,42.000598,4316.548908,40.657960,1.063224366,100.0,0.625219,51.310241,1.063224
8,United Kingdom,2000,16.780617,47,1.182956,52.131929,28149.870010,11.063614,8.339555322000001,100.0,0.660931,36.980357,8.339556
9,United States,2000,14.026010,48,3.376857,25.043635,36334.908780,8.110464,1.852973519,100.0,1.000000,53.032078,1.852973

In [60]:
df4.to_csv (r'C:/Users/Arshad/Documents/Salu/merge/gs-stata_merged.csv')